version: '3'

services:
  postgres:
    image: postgres:14-alpine
    container_name: postgres
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: meters_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 7893
    volumes:
      - postgres_data:/var/lib/postgresql/data

  rabbitmq:
    image: rabbitmq:3-management-alpine
    container_name: rabbitmq
    ports:
      - "5672:5672"
      - "15672:15672"
    environment:
      RABBITMQ_DEFAULT_USER: guest
      RABBITMQ_DEFAULT_PASS: guest

  billing-worker:
    build:
      context: .
      dockerfile: Dockerfile.worker
    depends_on:
      - postgres
      - rabbitmq
    environment:
      DB_HOST: postgres
      RABBITMQ_HOST: rabbitmq

  api:
    build:
      context: .
      dockerfile: Dockerfile.api
    ports:
      - "5000:5000"
    depends_on:
      - postgres
      - rabbitmq
    environment:
      DB_HOST: postgres
      RABBITMQ_HOST: rabbitmq
      POSTGRES_PASSWORD: 7893

volumes:
  postgres_data: 